-- The Latent Review — FICTION AS A FOURTH TRUTH STANDARD (R-029)
--
-- Ruled by both editors on the diff of this branch: the journal publishes
-- declared fiction under a fourth truth standard, joining Reported, Opinion and
-- First Person. Every piece still runs under exactly one standard, and the
-- standard is displayed with the piece as provenance is.
--
-- What this migration does: widens the truth_standard CHECK on
-- public.submissions from three values to four.
--
-- WHY THE DATABASE IS THE LAST OF NINE PLACES, NOT THE ONLY ONE.
-- truth_standard is enumerated in nine sites across this repository: this
-- CHECK, the published-content Zod schema (src/content.config.ts), the machine
-- contract (/agent-api.json), the agent door's documented contract
-- (/for-agents), the human form (/submit), the machine-readable prose
-- (/llms.txt), the display label and description maps (src/lib/site.ts — two
-- sites), and the article template's frontmatter comment
-- (src/content/articles/_example.md), which is what an author or editor reads
-- when composing a piece.
-- Widening this constraint alone would produce a standard the database accepts,
-- the build rejects, the form never offers, the door never documents and the
-- page renders unlabelled — enforcing-and-broken, which the CSP correction
-- (2026-07-29) settled is worse than honest-and-narrow. All nine move together
-- in this branch, with the Charter and the editorial criteria.
--
-- WHY A STANDARD AND NOT A FORM. The three existing standards all describe one
-- axis: the relation between the text and reality — verified, argued, or
-- attested-and-unverifiable. Fiction is a fourth position on that same axis. Were
-- it a separate "form" field instead, every fiction piece would still have to
-- declare one of the three, and all three would be false: a story is not
-- Reported, and First Person is defined as testimony narrated by the one who
-- lived it, which a fictional narrator did not. A separate form field forces a
-- false value into a not-null column. A fourth standard does not.
--
-- THE CONSTRAINT IS FOUND, NOT NAMED BY GUESS. The original CHECK was declared
-- inline in 20260717000000_editors_desk.sql, so its name was generated by
-- Postgres rather than chosen. Rather than assume 'submissions_truth_standard_check',
-- this migration locates the check constraint that mentions the column and drops
-- it by whatever name it actually has, then adds a NAMED replacement so the next
-- migration to touch this never has to guess either.
--
-- NOTHING IS GRANTED OR REVOKED HERE. anon's column-restricted INSERT already
-- covers truth_standard; widening the permitted values hands anon no new column
-- and no new privilege. The probe asserts that, because a widening that quietly
-- changed the intake surface would be a break in the public door.

do $$
declare
  conname_found text;
begin
  select con.conname into conname_found
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
  where nsp.nspname = 'public'
    and rel.relname = 'submissions'
    and con.contype = 'c'
    and pg_get_constraintdef(con.oid) ilike '%truth_standard%'
  limit 1;

  if conname_found is null then
    raise exception 'no CHECK constraint mentioning truth_standard found on public.submissions — refusing to proceed, because adding a second overlapping CHECK would leave the old one silently enforcing three values';
  end if;

  execute format('alter table public.submissions drop constraint %I', conname_found);
  raise notice 'dropped prior truth_standard CHECK: %', conname_found;
end $$;

alter table public.submissions
  add constraint submissions_truth_standard_check
  check (truth_standard in ('reported', 'opinion', 'first-person', 'fiction'));

-- Probe. Inspects the constraint DEFINITION, not the table's behaviour: it
-- asserts that the named CHECK exists, that its definition mentions fiction, and
-- that exactly ONE check constraint on this table mentions truth_standard — that
-- last one being the assertion that matters, because a surviving second CHECK
-- would go on enforcing three values behind the new one. It also asserts anon's
-- intake privilege on the column is unchanged and that anon gained nothing.
-- Raises inside the transaction so a partial apply rolls back (the C-7
-- discipline).
--
-- What the probe does NOT do is insert rows: that the four values are accepted
-- and a bogus value still rejected was verified by executing this migration
-- against a real Postgres 16 in a throwaway container, not by anything in this
-- block. The distinction is worth keeping — a probe that claimed to test
-- behaviour it never exercises would be exactly the kind of guard that reads as
-- protection and is not.
do $$
declare
  problems text[] := '{}';
  def text;
begin
  select pg_get_constraintdef(con.oid) into def
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
  where nsp.nspname = 'public' and rel.relname = 'submissions'
    and con.conname = 'submissions_truth_standard_check';

  if def is null then
    problems := problems || 'named CHECK submissions_truth_standard_check is missing'::text;
  else
    if def not ilike '%fiction%' then
      problems := problems || 'CHECK does not admit fiction'::text;
    end if;
  end if;

  -- exactly one CHECK may mention the column; two would mean the old one
  -- survived and is still enforcing three values behind the new one.
  if (select count(*) from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
      where nsp.nspname = 'public' and rel.relname = 'submissions'
        and con.contype = 'c'
        and pg_get_constraintdef(con.oid) ilike '%truth_standard%') <> 1 then
    problems := problems || 'more than one CHECK mentions truth_standard — the old three-value constraint may still be enforcing'::text;
  end if;

  -- the intake privileges anon legitimately holds must be untouched
  if not has_column_privilege('anon', 'public.submissions', 'truth_standard', 'insert') then
    problems := problems || 'REGRESSION: anon lost insert on truth_standard'::text;
  end if;

  -- anon must not have gained anything from this widening
  if has_column_privilege('anon', 'public.submissions', 'status', 'insert') then
    problems := problems || 'REGRESSION: anon can insert status'::text;
  end if;

  if array_length(problems, 1) is not null then
    raise exception 'fiction truth-standard migration failed its own probe: %',
      array_to_string(problems, '; ');
  end if;
end $$;
